# Introduction to Numpy

**NumPy** is a open source Python library commonly used in machine learning. It was created in 2005 by developer Travis Oliphant
*    Its primary function is to provide support for large, multi-dimensional arrays and matrices
*    Also has a collection of mathematical functions to operate on these arrays efficiently
*    Is a building block for many other python libraries, including pandas, which we'll dive into next


Here we import numpy using the np abbreviation. This has become the standard import method, so if you look up numpy code on the web, you'll likely see the same abbreviation.

In [ ]:
import numpy as np

We can convert regular python arrays to numpy arrays:

In [ ]:
original_array = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
np.array(original_array)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

We can create arrays of zeros:

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Or arrays of ones:

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Or arrays of random values between 0 and 1:

In [ ]:
np.random.rand(3,4)

array([[0.41923141, 0.69416281, 0.62100593, 0.61161454],
       [0.25027425, 0.21691276, 0.19469824, 0.33629277],
       [0.36064681, 0.16464641, 0.74541081, 0.73877372]])

We can also check the shape of any given numpy array by checking the shape attribute:

In [ ]:
np.random.rand(3,4).shape  # gives us the rows, columns of the array

(3, 4)

Or arrays of random integers of our choosing:

In [ ]:
# np.random.rand(start,end,shape_of_array)
np.random.randint(0,11,(3,4)) # generates random integers between 0 and 10

We can access array elements by specifying the row and column:

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a[0,0])
print(a[1,2])
print(a[2,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
7
12


We can also slice an array similar to how we slice lists:

In [ ]:
a

In [ ]:
a[1, 1:3] #access the second row starting at column index 1, up to but not including column index 3

In [ ]:
a[1, 2:] #access the second row starting at column index 2

array([7, 8])

In [ ]:
a[1, :] #access the entire second row

# Introduction to Pandas and Dataframes

**Pandas** is a popular Python library, used for statistical analysis. We operate on **dataframes**, which you can think of as "Excel sheets as variables in Python".

In [ ]:
import pandas as pd # because we don't want to type 'pandas', only 'pd'. Think of all the hours of typing saved!

## Importing data

Now, let's import some data! We do this using the `read_csv` function within the `pd` library, so we call it with `pd.read_csv`. We tell it one thing: the location of the file to be read.

Let's get started by importing a CSV file, which are plain-text versions of data values! You should have some sample CSVs on your machines already. Double check to make sure they're in the **same folder as this notebook**

Some sample CSV files can be found in our server's `Resources` folder. To use them, you'll need to go to the homepage, download the CSV files from the `Resources` folder, and **re-upload to the same folder as this notebook**.

Once you're ready, run the next cell to store all the data in a CSV in a single variable:

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/iamamangosteen/pythonforbusiness/master/gdp_asia.csv")

In [ ]:
data

country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0          Afghanistan      779.445314      820.853030      853.100710   
1              Bahrain     9867.084765    11635.799450    12753.275140   
2           Bangladesh      684.244172      661.637458      686.341554   
3             Cambodia      368.469286      434.038336      496.913648   
4                China      400.448611      575.987001      487.674018   
5      Hong Kong China     3054.421209     3629.076457     4692.648272   
6                India      546.565749      590.061996      658.347151   
7            Indonesia      749.681655      858.900271      849.289770   
8                 Iran     3035.326002     3290.257643     4187.329802   
9                 Iraq     4129.766056     6229.333562     8341.737815   
10              Israel     4086.522128     5385.278451     7105.630706   
11               Japan     3216.956347     4317.694365     6576.649461   
12              Jordan     1546.907807     1886.080591     2348.009158   
13     Korea Dem. Rep.     1088.277758     1571.134655     1621.693598   
14          Korea Rep.     1030.592226     1487.593537     1536.344387   
15              Kuwait   108382.352900   113523.132900    95458.111760   
16             Lebanon     4834.804067     6089.786934     5714.560611   
17            Malaysia     1831.132894     1810.066992     2036.884944   
18            Mongolia      786.566857      912.662609     1056.353958   
19             Myanmar      331.000000      350.000000      388.000000   
20               Nepal      545.865723      597.936356      652.396859   
21                Oman     1828.230307     2242.746551     2924.638113   
22            Pakistan      684.597144      747.083529      803.342742   
23         Philippines     1272.880995     1547.944844     1649.552153   
24        Saudi Arabia     6459.554823     8157.591248    11626.419750   
25           Singapore     2315.138227     2843.104409     3674.735572   
26           Sri Lanka     1083.532030     1072.546602     1074.471960   
27               Syria     1643.485354     2117.234893     2193.037133   
28              Taiwan     1206.947913     1507.861290     1822.879028   
29            Thailand      757.797418      793.577415     1002.199172   
30             Vietnam      605.066492      676.285448      772.049160   
31  West Bank and Gaza     1515.592329     1827.067742     2198.956312   
32          Yemen Rep.      781.717576      804.830455      825.623201   

    gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0       836.197138      739.981106      786.113360      978.011439   
1     14804.672700    18268.658390    19340.101960    19211.147310   
2       721.186086      630.233627      659.877232      676.981866   
3       523.432314      421.624026      524.972183      624.475478   
4       612.705693      676.900092      741.237470      962.421381   
5      6197.962814     8315.928145    11186.141250    14560.530510   
6       700.770611      724.032527      813.337323      855.723538   
7       762.431772     1111.107907     1382.702056     1516.872988   
8      5906.731805     9613.818607    11888.595080     7608.334602   
9      8931.459811     9576.037596    14688.235070    14517.907110   
10     8393.741404    12786.932230    13306.619210    15367.029200   
11     9847.788607    14778.786360    16610.377010    19384.105710   
12     2741.796252     2110.856309     2852.351568     4161.415959   
13     2143.540609     3701.621503     4106.301249     4106.525293   
14     2029.228142     3030.876650     4657.221020     5622.942464   
15    80894.883260   109347.867000    59265.477140    31354.035730   
16     6006.983042     7486.384341     8659.696836     7640.519521   
17     2277.742396     2849.094780     3827.921571     4920.355951   
18     1226.041130     1421.741975     1647.511665     2000.603139   
19      349.000000      357.000000      371.000000      424.000000   
20      676.442225      674.

Printing is a bit unwieldy because of all the data. To read just a bit of info from the beginning, which lets you check if everything imported correctly, use `.head()`:

In [ ]:
data.head()

country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0  Afghanistan      779.445314      820.853030      853.100710   
1      Bahrain     9867.084765    11635.799450    12753.275140   
2   Bangladesh      684.244172      661.637458      686.341554   
3     Cambodia      368.469286      434.038336      496.913648   
4        China      400.448611      575.987001      487.674018   

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0      836.197138      739.981106      786.113360      978.011439   
1    14804.672700    18268.658390    19340.101960    19211.147310   
2      721.186086      630.233627      659.877232      676.981866   
3      523.432314      421.624026      524.972183      624.475478   
4      612.705693      676.900092      741.237470      962.421381   

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0      852.395945      649.341395      635.341351      726.734055   
1    18524.024060    19035.579170    20292.016790    23403.559270   
2      751.979403      837.810164      972.770035     1136.390430   
3      683.895573      682.303175      734.285170      896.226015   
4     1378.904018     1655.784158     2289.234136     3119.280896   

   gdpPercap_2007  
0      974.580338  
1    29796.048340  
2     1391.253792  
3     1713.778686  
4     4959.114854

Notice that the column headings are each of the columns in the CSV file, and the row headings are just numbers. This is OK, but not quite right--we want each row heading to be the country. In pandas terminology, we want to **set the country column as the index**. To do this, we re-import, and specify an `index_col`:

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/iamamangosteen/pythonforbusiness/master/gdp_asia.csv", index_col="country")

In [ ]:
data.head()

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                       
Afghanistan      779.445314      820.853030      853.100710      836.197138   
Bahrain         9867.084765    11635.799450    12753.275140    14804.672700   
Bangladesh       684.244172      661.637458      686.341554      721.186086   
Cambodia         368.469286      434.038336      496.913648      523.432314   
China            400.448611      575.987001      487.674018      612.705693   

             gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                       
Afghanistan      739.981106      786.113360      978.011439      852.395945   
Bahrain        18268.658390    19340.101960    19211.147310    18524.024060   
Bangladesh       630.233627      659.877232      676.981866      751.979403   
Cambodia         421.624026      524.972183      624.475478      683.895573   
China            676.900092      741.237470      962.421381     1378.904018   

             gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                      
Afghanistan      649.341395      635.341351      726.734055      974.580338  
Bahrain        19035.579170    20292.016790    23403.559270    29796.048340  
Bangladesh       837.810164      972.770035     1136.390430     1391.253792  
Cambodia         682.303175      734.285170      896.226015     1713.778686  
China           1655.784158     2289.234136     3119.280896     4959.114854

Now, the first two rows look a bit weird, but that's pandas' way of telling us that "country" is an index column. You can have multiple index columns, but that's beyond the scope of this class.

<hr>

## Some DataFrame operations

Some useful functions you can do with DataFrames below. Try them out, and see what they do!

In [ ]:
data.describe()

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
count       33.000000       33.000000       33.000000       33.000000   
mean      5195.484004     5787.732940     5729.369625     5971.173374   
std      18634.890865    19506.515959    16415.857196    14062.591362   
min        331.000000      350.000000      388.000000      349.000000   
25%        749.681655      793.577415      825.623201      836.197138   
50%       1206.947913     1547.944844     1649.552153     2029.228142   
75%       3035.326002     3290.257643     4187.329802     5906.731805   
max     108382.352900   113523.132900    95458.111760    80894.883260   

       gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
count       33.000000       33.000000       33.000000       33.000000   
mean      8187.468699     7791.314020     7434.135157     7608.226508   
std      19087.502918    11815.777923     8701.176499     8090.262765   
min        357.000000      371.000000      424.000000      385.000000   
25%       1049.938981     1175.921193     1443.429832     1704.686583   
50%       2571.423014     3195.484582     4106.525293     4106.492315   
75%       8597.756202    11210.089480    12954.791010    11643.572680   
max     109347.867000    59265.477140    33693.175250    28118.429980   

       gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
count       33.000000       33.000000       33.000000       33.000000  
mean      8639.690248     9834.093295    10174.090397    12473.026870  
std       9727.431088    11094.180481    11150.719203    14154.937343  
min        347.000000      415.000000      611.000000      944.000000  
25%       1785.402016     1902.252100     2092.712441     2452.210407  
50%       3726.063507     3645.379572     4090.925331     4471.061906  
75%      15215.657900    19702.055810    19233.988180    22316.192870  
max      34932.919590    40300.619960    36023.105400    47306.989780

In [ ]:
data.info() # tells you about the type of data in each column, and some general info

<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, Afghanistan to Yemen Rep.
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   gdpPercap_1952  33 non-null     float64
 1   gdpPercap_1957  33 non-null     float64
 2   gdpPercap_1962  33 non-null     float64
 3   gdpPercap_1967  33 non-null     float64
 4   gdpPercap_1972  33 non-null     float64
 5   gdpPercap_1977  33 non-null     float64
 6   gdpPercap_1982  33 non-null     float64
 7   gdpPercap_1987  33 non-null     float64
 8   gdpPercap_1992  33 non-null     float64
 9   gdpPercap_1997  33 non-null     float64
 10  gdpPercap_2002  33 non-null     float64
 11  gdpPercap_2007  33 non-null     float64
dtypes: float64(12)
memory usage: 3.4+ KB


In [ ]:
data.mean()

gdpPercap_1952     5195.484004
gdpPercap_1957     5787.732940
gdpPercap_1962     5729.369625
gdpPercap_1967     5971.173374
gdpPercap_1972     8187.468699
gdpPercap_1977     7791.314020
gdpPercap_1982     7434.135157
gdpPercap_1987     7608.226508
gdpPercap_1992     8639.690248
gdpPercap_1997     9834.093295
gdpPercap_2002    10174.090397
gdpPercap_2007    12473.026870
dtype: float64

In [ ]:
data.max()

gdpPercap_1952    108382.35290
gdpPercap_1957    113523.13290
gdpPercap_1962     95458.11176
gdpPercap_1967     80894.88326
gdpPercap_1972    109347.86700
gdpPercap_1977     59265.47714
gdpPercap_1982     33693.17525
gdpPercap_1987     28118.42998
gdpPercap_1992     34932.91959
gdpPercap_1997     40300.61996
gdpPercap_2002     36023.10540
gdpPercap_2007     47306.98978
dtype: float64

In [ ]:
data.columns # gives the column names. No parentheses, this is an attribute stored within the dataframe variable, not a function.

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')

In [ ]:
data.index # gives us the row names

Index(['Afghanistan', 'Bahrain', 'Bangladesh', 'Cambodia', 'China',
       'Hong Kong China', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel',
       'Japan', 'Jordan', 'Korea Dem. Rep.', 'Korea Rep.', 'Kuwait', 'Lebanon',
       'Malaysia', 'Mongolia', 'Myanmar', 'Nepal', 'Oman', 'Pakistan',
       'Philippines', 'Saudi Arabia', 'Singapore', 'Sri Lanka', 'Syria',
       'Taiwan', 'Thailand', 'Vietnam', 'West Bank and Gaza', 'Yemen Rep.'],
      dtype='object', name='country')

In [ ]:
data.T # stands for "transpose" - flips the dataframe along the diagonal so the rows become the columns and vice versa

country         Afghanistan       Bahrain   Bangladesh     Cambodia  \
gdpPercap_1952   779.445314   9867.084765   684.244172   368.469286   
gdpPercap_1957   820.853030  11635.799450   661.637458   434.038336   
gdpPercap_1962   853.100710  12753.275140   686.341554   496.913648   
gdpPercap_1967   836.197138  14804.672700   721.186086   523.432314   
gdpPercap_1972   739.981106  18268.658390   630.233627   421.624026   
gdpPercap_1977   786.113360  19340.101960   659.877232   524.972183   
gdpPercap_1982   978.011439  19211.147310   676.981866   624.475478   
gdpPercap_1987   852.395945  18524.024060   751.979403   683.895573   
gdpPercap_1992   649.341395  19035.579170   837.810164   682.303175   
gdpPercap_1997   635.341351  20292.016790   972.770035   734.285170   
gdpPercap_2002   726.734055  23403.559270  1136.390430   896.226015   
gdpPercap_2007   974.580338  29796.048340  1391.253792  1713.778686   

country               China  Hong Kong China        India    Indonesia  \
gdpPercap_1952   400.448611      3054.421209   546.565749   749.681655   
gdpPercap_1957   575.987001      3629.076457   590.061996   858.900271   
gdpPercap_1962   487.674018      4692.648272   658.347151   849.289770   
gdpPercap_1967   612.705693      6197.962814   700.770611   762.431772   
gdpPercap_1972   676.900092      8315.928145   724.032527  1111.107907   
gdpPercap_1977   741.237470     11186.141250   813.337323  1382.702056   
gdpPercap_1982   962.421381     14560.530510   855.723538  1516.872988   
gdpPercap_1987  1378.904018     20038.472690   976.512676  1748.356961   
gdpPercap_1992  1655.784158     24757.603010  1164.406809  2383.140898   
gdpPercap_1997  2289.234136     28377.632190  1458.817442  3119.335603   
gdpPercap_2002  3119.280896     30209.015160  1746.769454  2873.912870   
gdpPercap_2007  4959.114854     39724.978670  2452.210407  3540.651564   

country                 Iran          Iraq  ...  Philippines  Saudi Arabia  \
gdpPercap_1952   3035.326002   4129.766056  ...  1272.880995   6459.554823   
gdpPercap_1957   3290.257643   6229.333562  ...  1547.944844   8157.591248   
gdpPercap_1962   4187.329802   8341.737815  ...  1649.552153  11626.419750   
gdpPercap_1967   5906.731805   8931.459811  ...  1814.127430  16903.048860   
gdpPercap_1972   9613.818607   9576.037596  ...  1989.374070  24837.428650   
gdpPercap_1977  11888.595080  14688.235070  ...  2373.204287  34167.762600   
gdpPercap_1982   7608.334602  14517.907110  ...  2603.273765  33693.175250   
gdpPercap_1987   6642.881371  11643.572680  ...  2189.634995  21198.261360   
gdpPercap_1992   7235.653188   3745.640687  ...  2279.324017  24841.617770   
gdpPercap_1997   8263.590301   3076.239795  ...  2536.534925  20586.690190   
gdpPercap_2002   9240.761975   4390.717312  ...  2650.921068  19014.541180   
gdpPercap_2007  11605.714490   4471.061906  ...  3190.481016  21654.831940   

country            Singapore    Sri Lanka        Syria        Taiwan  \
gdpPercap_1952   2315.138227  1083.532030  1643.485354   1206.947913   
gdpPercap_1957   2843.104409  1072.546602  2117.234893   1507.861290   
gdpPercap_1962   3674.735572  1074.471960  2193.037133   1822.879028   
gdpPercap_1967   4977.418540  1135.514326  1881.923632   2643.858681   
gdpPercap_1972   8597.756202  1213.395530  2571.423014   4062.523897   
gdpPercap_1977  11210.089480  1348.775651  3195.484582   5596.519826   
gdpPercap_1982  15169.161120  1648.079789  3761.837715   7426.354774   
gdpPercap_1987  18861.530810  1876.766827  3116.774285  11054.561750   
gdpPercap_1992  24769.891200  2153.739222  3340.542768  15215.657900   
gdpPercap_1997  33519.476600  2664.477257  4014.238972  20206.820980   
gdpPercap_2002  36023.105400  3015.378833  4090.925331  23235.423290   
gdpPercap_2007  47143.179640  3970.095407  4184.548089  28718.276840   

country            Thailand      Vietnam  West Bank and Gaza   Yemen Rep.  
gdpPercap_1952   757.797418   605.066492         1515.592329   781.717576  
gdpPercap

### <font color="red">Exercise 1: Import and check</font>

Import the data from the CSV file from another continent, and check how many rows of data it has.

In [ ]:
africa = pd.read_csv("https://raw.githubusercontent.com/iamamangosteen/pythonforbusiness/master/gdp_africa.csv", index_col="country")

In [ ]:
print(len(africa))

52


<hr>

## Reading and filtering data in DataFrames

There are many, many ways of accessing data in DataFrames. Here are a few ways--you can read up on other ways at the [Pandas DataFrame documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html) page. It's worth clicking over just to see the variety of functions you can call to handle DataFrames!

Here, though, we'll start with accessing information the way you'd expect, by row and column:

In [ ]:
data.head() #just to see the data

In [ ]:
data.iloc[0,0] #Row 0, column 0

779.4453145

In [ ]:
data.iloc[1,0] #Row 1, column 0

9867.084765

In [ ]:
# We can access a whole series of data using slicing:
print(data.iloc[0:4,0]) #Rows 0 to 3, column 0

country
Afghanistan     779.445314
Bahrain        9867.084765
Bangladesh      684.244172
Cambodia        368.469286
Name: gdpPercap_1952, dtype: float64


In [ ]:
# The row and column numbers aren't very expressive. We can use names instead with loc, instead of iloc:

data.loc["Afghanistan","gdpPercap_1952"]

In [ ]:
data.loc["China","gdpPercap_1952"]

In [ ]:
data.loc["Afghanistan":"China","gdpPercap_1952"] #Note: slicing with .loc is *inclusive*

In [ ]:
data.loc["Afghanistan":"China", :]

In [ ]:
#You can select individual rows or columns by creating a list inside loc:

rows_to_show = ["Singapore", "Malaysia", "Indonesia"]
cols_to_show = ["gdpPercap_1952", "gdpPercap_2007"]

data.loc[rows_to_show, cols_to_show]

### <font color="red">Exercise 2: Get data</font>

Import the necessary CSV file, and set up a DataFrame for the GDP data of Canada, the United States, and Mexico for last decade. Your result should look like this:

|                 | gdpPercap_2002 | gdpPercap_2007 |
| --------------- | -------------- | -------------- |
| Canada          | 33328.96507    | 36319.23501    |
| United States   | 39097.09955    | 42951.65309    |
| Mexico          | 10742.44053    | 11977.57496    |

In [ ]:
americas = pd.read_csv("https://raw.githubusercontent.com/iamamangosteen/pythonforbusiness/master/gdp_africa.csv", index_col="country")
rows_to_show = ["Canada","United States","Mexico"]
cols_to_show = ["gdpPercap_2002","gdpPercap_2007"]

americas.loc[rows_to_show, cols_to_show]

<hr>

## Filtering data

Here's one of the most powerful features of DataFrames--being able to quickly work with large chunks of data. If you had to do this with for loops, it'd be a bit of pain to filter everything out item by item, not to mention having to reconstruct your lists one by one.

In [ ]:
# we'll illustrate filtering with a small subset to it's easier to see what's happening
data = pd.read_csv("gdp_asia.csv", index_col="country")
subset = data.loc["Afghanistan":"China","gdpPercap_1952"]
subset.head()

In [ ]:
# This condition generates a "truth table" of sorts:
subset > 500

In [ ]:
# We can store the condition table as a variable, and apply it as a filter, using square brackets:
its_over_500 = subset > 500
subset[its_over_500]

In [ ]:
# In one line, we could do this (but it's harder to read):
subset[subset>500]

## More Filtering

Take a look at what's being done, and try to figure it out, particularly when it comes to the two-condition criteria!

In [ ]:
# Can you figure out what's being done in the below code?

#Note: this uses the shorthand method of accessing a column of data (instead of .loc)

dataAll = pd.read_csv("gdp_pop_all.csv", index_col = "country")
#imports data in, sets index column

criteria = (dataAll["continent"] == "Asia") & (dataAll["gdpPercap_2007"] > 9000)
#creates criteria where continent = Asia AND 2007gdp > 9000

dataAll["gdp_2007"] = dataAll["gdpPercap_2007"] * dataAll["pop_2007"]
#creates a new column called gdp_2007 that calculates the actual GDP (not per capita)

dataAll[criteria][["gdpPercap_2007","pop_2007", "gdp_2007"]]
#filters the dataframe based on our criteria, selecting only 3 columns: gdpPercap_2007, pop_2007, and gdp_2007

### <font color="red">Exercise 3: African data and filtering</font>

* Read data from the Africa file
* Find the Per Capita GDP of Egypt in 2007
* Find countries whose Per Capita GDP exceeded Egypt's that year.

There should be 9 countries.

In [ ]:
africa = pd.read_csv("https://raw.githubusercontent.com/iamamangosteen/pythonforbusiness/master/gdp_africa.csv", index_col="country")

africa.head()

In [ ]:
egypt_2007 = africa.loc["Egypt", "gdpPercap_2007"]

In [ ]:
criteria = africa["gdpPercap_2007"] > egypt_2007
africa.loc[criteria][["gdpPercap_2007"]]

### <font color="red">Exercise 4: What does this do?</font>

What do each of the lines in this chunk of code do? Run it, find out, and explain to someone sitting next to you.

In [ ]:
first = pd.read_csv('gdp_pop_all.csv', index_col='country')

criteria = first['continent'] == 'Americas'
second = first[criteria]
# define a filter criteria and apply it to the dataframe, saving the result in the variable named 'second'

third = second.drop('Puerto Rico')
fourth = third.drop('continent', axis = 1)
#Drop the row 'Puerto Rico' and the column 'continent' by specifying the 'axis' parameter

fourth.to_csv('result.csv')
fourth.to_excel('result.xlsx')
#export the results to CSV and Excel documents

## Inserting data

Inserting column data into your DataFrames is straightforward. Just add it in:

What about adding rows onto your DataFrame?

In [ ]:
#Some starter code:
df = pd.read_csv("gdp_asia.csv", index_col="country")
rows = ['Singapore','Malaysia']
cols = ['gdpPercap_1952','gdpPercap_1957']
subset1 = df.loc[rows,cols]

rows = ['Thailand','Indonesia']
cols = ['gdpPercap_1952','gdpPercap_1957']
subset2 = df.loc[rows,cols]

rows = ['Thailand','Indonesia']
cols = ['gdpPercap_1952','gdpPercap_2007']
subset3 = df.loc[rows,cols]

It works great if the columns are the same in both dataframes:

In [ ]:
subset1.append(subset2)

But can cause some trouble if the columns differ at all:

In [ ]:
subset1.append(subset3)

### Merging Dataframes

In [ ]:
# Some starter code:
subset1 = data.loc["Afghanistan":"China", "gdpPercap_1952":"gdpPercap_1957"]
subset2 = data.loc["Afghanistan":"China", "gdpPercap_2002":"gdpPercap_2007"]

In [ ]:
merged = subset1.merge(subset2, left_index=True, right_index=True) #we specify that we're matching the indices (i.e. the rows) of the left dataframe with the indices of the right dataframe
merged

There's also .join and .concat methods for joining dataframes, but we leave these as an exercise for the reader!

### <font color="red">Exercise 5: European data analysis</font>

Import the GDP data for Europe. Write an expression to select each of the following:

* GDP per capita for all countries in 1982.
* GDP per capita for Denmark for all years.
* GDP per capita for all countries for years after 1985.
* GDP per capita for each country in 2007 as a multiple of GDP per capita for that country in 1952. Show a DataFrame with 1952, 2007, and "2007 vs. 1952", for example:

|                        | gdpPercap_1952 | gdpPercap_2007  | 2007/1952 |
| ---------------------- | -------------- | --------------  | --------- |
| Albania                | 1601.056136    | 5937.029526     | 3.708196  |
| Austria                | 6137.076492    | 36126.492700    | 5.886596  |
| Belgium                | 8343.105127    | 33692.605080    | 4.038377  |
| Bosnia and Herzegovina | 973.533195     | 7446.298803     | 7.648736  |
| Bulgaria               | 2444.286648    | 10680.792820    | 4.369697  |

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/iamamangosteen/pythonforbusiness/master/gdp_europe.csv', index_col='country')

In [ ]:
# a) GDP for all countries in 1982


In [ ]:
# b) GDP for Denmark for all years


In [ ]:
# c) GDP after 1985


In [ ]:
# d) GDP per capita for each country in 2007 as a multiple of GDP per capita for that country in 1952.
