<a href="https://colab.research.google.com/github/Potatoed7/AI-FES-pynotebooks/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hopefully can use as reference.

In [ ]:
# prompt: machine learning module with sklearn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load the iris dataset
iris_data = load_iris()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(iris_data["data"], iris_data["target"], random_state=0)

# Create a KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)

# Train the classifier
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = knn.score(X_test, y_test)
print(accuracy)


0.9736842105263158


Actual work

In [30]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import csv
from pathlib import Path
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import BorderlineSMOTE
from imblearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score, classification_report, confusion_matrix, accuracy_score, roc_auc_score, roc_curve, precision_recall_curve, average_precision_score
from sklearn.metrics import homogeneity_score, silhouette_score
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import MiniBatchKMeans, DBSCAN


# Define a function to prep our data
def prep_data(df: pd.DataFrame) -> (np.ndarray, np.ndarray):
    """
    Convert the DataFrame into two variable
    X: data columns (V1 - V28)
    y: lable column
    """
    X = df.iloc[:, 2:30].values
    y = df.diffculty.values
    return X, y

# Define a function to create a scatter plot of our data and labels
def plot_data(X: np.ndarray, y: np.ndarray):
    plt.scatter(X[y == 0, 0], X[y == 0, 1], label="Class #0", alpha=0.5, linewidth=0.15)
    plt.scatter(X[y == 1, 0], X[y == 1, 1], label="Class #1", alpha=0.5, linewidth=0.15, c='r')
    plt.legend()
    return plt.show()

In [2]:
#get dataset
datasheet_test = "https://raw.githubusercontent.com/Potatoed7/AI-FES-pynotebooks/blob/main/AI%20data%20-%20100%20only%20test.csv"
datasheet_test2 = "https://raw.githubusercontent.com/Potatoed7/AI-FES-pynotebooks/main/AI%20data%20-%20100%20only%20test.csv"

In [3]:
#import the file into a dataframe, i.e. a "spreadsheet" in Python
dftest = pd.read_csv(datasheet_test2, nrows=99)

In [ ]:
dftest

# ***Working AI***

In [36]:
# prompt: Using dataframe dftest: write a machine learning program using this dataset to give the difficulty of the equation between 'number 1' and 'number 2'

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier

# Load the data
df = dftest

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df[['Number 1','Operation','Number 2', 'Result']], df['diffculty'], test_size=0.2)

# Train a random forest classifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
print(y_pred)

# Evaluate the accuracy of the classifier
accuracy = model.score(X_test, y_test)
print(accuracy)


[ 3  1  3  1  2  3  1  3  2 10  2  2  2  2  3  2  2  1  1  1]
0.65


In [37]:
X_test

Number 1  Operation  Number 2     Result
74        39          4        80     0.4875
40        93          2        39    54.0000
37       -88          3       -33  2904.0000
78        61          2         6    55.0000
54        88          1       -88     0.0000
29       -50          3       -40  2000.0000
69        26          1        45    71.0000
8        -52          3        69 -3588.0000
95       -88          1       -88  -176.0000
70        55          4      -100    -0.5500
22       -85          1        87     2.0000
68       -54          2       -46    -8.0000
80        -4          2        89   -93.0000
91       -76          2         6   -82.0000
92       -91          3       -57  5187.0000
88        70          1       -92   -22.0000
44         4          4        96     0.0417
66        98          2       -20   118.0000
5          9          1        30    39.0000
11       -33          1        67    34.0000

In [38]:
#using dataFrames?
test2 = pd.DataFrame([[78, 4, -8, -9.75]],columns = ['Number 1', 'Operation', 'Number 2', 'Result'])

print(test2)

   Number 1  Operation  Number 2  Result
0        78          4        -8   -9.75


In [39]:
model.predict(test2)

array([3])

In [40]:
dftest = pd.read_csv(datasheet_test2)

In [41]:
dftest

Number 1  Operation  Number 2       Result  diffculty
0            1          3       -99   -99.000000        3.0
1          -99          2        23  -122.000000        3.0
2           73          3        78  5694.000000        3.0
3           15          2        51   -36.000000        2.0
4          -62          1        44   -18.000000        2.0
...        ...        ...       ...          ...        ...
1494        45          1       -61   -16.000000        NaN
1495       -39          3       -63  2457.000000        NaN
1496        39          2       -81   120.000000        NaN
1497       -50          3       -58  2900.000000        NaN
1498       -45          4        76    -0.592105        NaN

[1499 rows x 5 columns]

In [43]:
dftest = dftest.drop(["diffculty"], axis=1)
#dftest = dftest.drop(columns=['diffculty'])

In [44]:
dftest

Number 1  Operation  Number 2       Result
0            1          3       -99   -99.000000
1          -99          2        23  -122.000000
2           73          3        78  5694.000000
3           15          2        51   -36.000000
4          -62          1        44   -18.000000
...        ...        ...       ...          ...
1494        45          1       -61   -16.000000
1495       -39          3       -63  2457.000000
1496        39          2       -81   120.000000
1497       -50          3       -58  2900.000000
1498       -45          4        76    -0.592105

[1499 rows x 4 columns]

In [45]:
y_pred = model.predict(dftest)

np.set_printoptions(threshold=np.inf)

In [46]:
y_pred

array([ 3,  3,  3,  2,  2,  1,  2,  3,  3,  9,  3,  1,  3,  2,  9,  1,  2,
        2,  2,  2,  3,  2,  2, 10,  2,  9,  5,  2,  2,  3,  3,  1,  2,  2,
        1, 10,  3,  3,  1,  2,  1,  2,  3,  2,  2,  2,  1,  1,  3,  3,  3,
        1,  1,  1,  2, 10,  3,  1,  1,  2,  3,  2,  2,  2,  9,  3,  1,  4,
        2,  1, 10,  3,  2,  2,  3,  2,  1,  1,  1, 10,  2,  2,  2,  5,  2,
        3,  5,  4,  2,  2,  1,  2,  3,  1,  3,  2,  1,  2,  2,  2,  3,  3,
        2,  2,  3,  2,  1,  3,  1,  1,  2,  2,  2,  2,  2,  3,  4,  5,  2,
        2,  2,  1,  2,  2,  3,  1,  3,  2,  9,  3,  5,  3,  3,  2,  2,  3,
        9,  9,  2, 10,  1, 10,  2,  5,  3,  1,  1,  2,  9,  3,  3,  2,  9,
        9,  3,  2,  3,  3,  9,  2,  2,  2,  2,  1,  2,  9,  2,  1, 10,  1,
        2,  2,  1,  2,  2,  2,  3,  2,  3,  2,  4,  2,  1,  4,  9,  3,  3,
        2,  3,  1,  3,  3,  2,  2,  2,  1,  3,  2,  1,  1,  3,  9,  2,  9,
        3,  5,  1,  1,  5,  2, 10,  3,  2,  2,  1, 10,  3,  2,  2,  1,  3,
        2,  1,  1,  9,  3

# ***Try to make it Gen AI***

In [ ]:
df = pd.read_csv(datasheet_test2)
df = df[:99]
print(df)
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['diffculty'], df[['Number 1','Operation','Number 2', 'Result']],  test_size=0.2)

# Train a random forest classifier
model2 = RandomForestClassifier()
model2.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model2.predict(X_test)
print(y_pred)

# Evaluate the accuracy of the classifier
accuracy = model2.score(X_test, y_test)
print(accuracy)

    Number 1  Operation  Number 2  Result  diffculty
0          1          3       -99   -99.0        3.0
1        -99          2        23  -122.0        3.0
2         73          3        78  5694.0        3.0
3         15          2        51   -36.0        2.0
4        -62          1        44   -18.0        2.0
..       ...        ...       ...     ...        ...
94       -38          3       -81  3078.0        3.0
95       -88          1       -88  -176.0        2.0
96        98          1        -8    90.0        1.0
97       -59          1       -97  -156.0        2.0
98        88          1       -98   -10.0        2.0

[99 rows x 5 columns]


AttributeError: 'Series' object has no attribute 'reshape'