<a href="https://colab.research.google.com/github/Potatoed7/AI-FES-pynotebooks/blob/main/Test(original).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hopefully can use as reference.

In [ ]:
# prompt: machine learning module with sklearn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load the iris dataset
iris_data = load_iris()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(iris_data["data"], iris_data["target"], random_state=0)

# Create a KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)

# Train the classifier
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = knn.score(X_test, y_test)
print(accuracy)


0.9736842105263158


Actual shit

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import csv
from pathlib import Path
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import BorderlineSMOTE
from imblearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score, classification_report, confusion_matrix, accuracy_score, roc_auc_score, roc_curve, precision_recall_curve, average_precision_score
from sklearn.metrics import homogeneity_score, silhouette_score
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import MiniBatchKMeans, DBSCAN


# Define a function to prep our data
def prep_data(df: pd.DataFrame) -> (np.ndarray, np.ndarray):
    """
    Convert the DataFrame into two variable
    X: data columns (V1 - V28)
    y: lable column
    """
    X = df.iloc[:, 2:30].values
    y = df.Class.values
    return X, y

# Define a function to create a scatter plot of our data and labels
def plot_data(X: np.ndarray, y: np.ndarray):
    plt.scatter(X[y == 0, 0], X[y == 0, 1], label="Class #0", alpha=0.5, linewidth=0.15)
    plt.scatter(X[y == 1, 0], X[y == 1, 1], label="Class #1", alpha=0.5, linewidth=0.15, c='r')
    plt.legend()
    return plt.show()

In [ ]:
#get dataset
datasheet_test = "https://raw.githubusercontent.com/Potatoed7/AI-FES-pynotebooks/blob/main/AI%20data%20-%20100%20only%20test.csv"
datasheet_test2 = "https://raw.githubusercontent.com/Potatoed7/AI-FES-pynotebooks/main/AI%20data%20-%20100%20only%20test.csv"

In [ ]:
#pd.set_option('display.max_columns', 700)
#pd.set_option('display.max_rows', 400)
#pd.set_option('display.min_rows', 10)
#pd.set_option('display.expand_frame_repr', True)

# -- idk what/how to use

In [ ]:
##### FAIL FAIL FAIL
#import the file into a dataframe, i.e. a "spreadsheet" in Python
dftest = pd.read_csv(datasheet_test, nrows=99)

HTTPError: HTTP Error 404: Not Found

In [ ]:
#import the file into a dataframe, i.e. a "spreadsheet" in Python
dftest = pd.read_csv(datasheet_test2, nrows=99)

In [ ]:
dftest

Number 1  Operation  Number 2  Result  diffculty
0          1          3       -99   -99.0          3
1        -99          2        23  -122.0          3
2         73          3        78  5694.0          3
3         15          2        51   -36.0          2
4        -62          1        44   -18.0          2
..       ...        ...       ...     ...        ...
94       -38          3       -81  3078.0          3
95       -88          1       -88  -176.0          2
96        98          1        -8    90.0          1
97       -59          1       -97  -156.0          2
98        88          1       -98   -10.0          2

[99 rows x 5 columns]

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Number 1'].plot(kind='hist', bins=20, title='Number 1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Operation'].plot(kind='hist', bins=20, title='Operation')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Number 2'].plot(kind='hist', bins=20, title='Number 2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='index', y='Number 1', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Number 1', y='Operation', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Operation', y='Number 2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Number 2', y='Result', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Number 1']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Number 1')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Operation']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Operation')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Number 2']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Number 2')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Result']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Result')

from matplotlib import pyplot as plt
_df_12['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['Number 1'].plot(kind='line', figsize=(8, 4), title='Number 1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['Operation'].plot(kind='line', figsize=(8, 4), title='Operation')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['Number 2'].plot(kind='line', figsize=(8, 4), title='Number 2')
plt.gca().spines[['top', 'right']].set_visible(False)

# ***Working AI***

In [ ]:
# prompt: Using dataframe dftest: write a machine learning program using this dataset to give the difficulty of the equation between 'number 1' and 'number 2'

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier

# Load the data
df = dftest

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df[['Number 1','Operation','Number 2', 'Result']], df['diffculty'], test_size=0.2)

# Train a random forest classifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
print(y_pred)

# Evaluate the accuracy of the classifier
accuracy = model.score(X_test, y_test)
print(accuracy)


[ 1  2  3  2  4  3  3  2  2 10  3  1  2  1  1  2  2  4  1  1]
0.7


In [ ]:
X_test

Number 1  Operation  Number 2       Result
83        88          4       -24    -3.670000
75       -25          3       -63  1575.000000
79        72          4       -65    -1.107692
9         59          4        53     1.113208
10       -75          1       -40  -115.000000
65       -98          3        31 -3038.000000
45        64          1        46   110.000000
84        83          2       -67   150.000000
13       -86          1        74   -12.000000
41        31          2        69   -38.000000
42        37          3       -78 -2886.000000
80        -4          2        89   -93.000000
52        15          1        75    90.000000
86        74          4       -88    -0.840900
21       -95          2       -69   -26.000000
61       -29          2        38   -67.000000
70        55          4      -100    -0.550000
56        79          3        57  4503.000000
72       -62          2        55  -117.000000
8        -52          3        69 -3588.000000

In [ ]:
print(X_test.shape)

(20, 4)


In [ ]:
test = np.array([78,-8,4])
print(test)
print(test.shape)
test = np.array([78,-8,4]).reshape(1, -1)
print(test)
print(test.shape)

[78 -8  4]
(3,)
[[78 -8  4]]
(1, 3)


In [ ]:
model.predict(test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: X has 3 features, but RandomForestClassifier is expecting 4 features as input.

In [ ]:
#using dataFrames?
test2 = pd.DataFrame([[78, 4, -8, -9.75]],columns = ['Number 1', 'Operation', 'Number 2', 'Result'])

print(test2)

   Number 1  Operation  Number 2  Result
0        78          4        -8   -9.75


In [ ]:
model.predict(test2)

array([4])

In [ ]:
dftest = pd.read_csv(datasheet_test2)

In [ ]:
dftest

In [ ]:
dftest.axes

[RangeIndex(start=100, stop=1499, step=1),
 Index(['Number 1', 'Operation', 'Number 2', 'Result', 'diffculty'], dtype='object')]

In [ ]:
dftest = dftest.drop(["diffculty"], axis=1)
#dftest = dftest.drop(columns=['diffculty'])

In [ ]:
dftest

Number 1  Operation  Number 2       Result
0            1          3       -99   -99.000000
1          -99          2        23  -122.000000
2           73          3        78  5694.000000
3           15          2        51   -36.000000
4          -62          1        44   -18.000000
...        ...        ...       ...          ...
1494        45          1       -61   -16.000000
1495       -39          3       -63  2457.000000
1496        39          2       -81   120.000000
1497       -50          3       -58  2900.000000
1498       -45          4        76    -0.592105

[1499 rows x 4 columns]

In [ ]:
y_pred = model.predict(dftest)

np.set_printoptions(threshold=np.inf)

In [ ]:
y_pred

array([ 3,  2,  3,  2,  2,  1,  2,  3,  4,  9,  3,  1,  3,  2,  9,  1,  2,
        2,  2,  2,  4,  2,  1, 10,  2,  3,  5,  2,  2,  3,  3,  1,  2,  2,
        1, 10,  3,  3,  1,  2,  1,  2,  3,  2,  4,  2,  1,  1,  3,  3,  3,
        1,  1,  1,  1,  4,  3,  1,  1,  2,  3,  2,  2,  2,  9,  3,  2,  4,
        2,  1, 10,  3,  2,  2,  4,  2,  1,  1,  1, 10,  2,  2,  2,  3,  2,
        3,  5,  4,  2,  2,  1,  2,  3,  1,  3,  2,  1,  2,  2,  2,  3,  3,
        2,  2,  3,  2,  1,  3,  2,  2,  2,  1,  2,  2,  2,  3,  4,  5,  2,
        1,  2,  1,  2,  2,  3,  1,  3,  2,  9,  3,  5,  3,  3,  1,  2,  3,
        9,  2,  2,  4,  1,  4,  2,  3,  3,  2,  1,  2,  4,  3,  3,  2,  3,
        3,  4,  2,  3,  3,  9,  2,  2,  2,  3,  1,  2,  9,  2,  1, 10,  1,
        2,  2,  1,  2,  2,  2,  3,  1,  3,  2,  4,  1,  1,  4,  9,  3,  3,
        2,  3,  1,  2,  3,  1,  2,  2,  2,  3,  2,  1,  1,  4,  4,  2,  9,
        3,  5,  1,  1,  5,  2, 10,  3,  2,  2,  1,  4,  3,  2,  2,  1,  2,
        2,  1,  1,  9,  3

In [ ]:
print(model.predict(dftest[151:155]))

[2 3 3 4]


# ***Try to make it Gen AI***

In [ ]:
df = pd.read_csv(datasheet_test2)
df = df[:99]
print(df)
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['diffculty'], df[['Number 1','Operation','Number 2', 'Result']],  test_size=0.2)

# Train a random forest classifier
model2 = RandomForestClassifier()
model2.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model2.predict(X_test)
print(y_pred)

# Evaluate the accuracy of the classifier
accuracy = model2.score(X_test, y_test)
print(accuracy)

    Number 1  Operation  Number 2  Result  diffculty
0          1          3       -99   -99.0        3.0
1        -99          2        23  -122.0        3.0
2         73          3        78  5694.0        3.0
3         15          2        51   -36.0        2.0
4        -62          1        44   -18.0        2.0
..       ...        ...       ...     ...        ...
94       -38          3       -81  3078.0        3.0
95       -88          1       -88  -176.0        2.0
96        98          1        -8    90.0        1.0
97       -59          1       -97  -156.0        2.0
98        88          1       -98   -10.0        2.0

[99 rows x 5 columns]


AttributeError: 'Series' object has no attribute 'reshape'