<a href="https://colab.research.google.com/github/Potatoed7/AI-FES-pynotebooks/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hopefully can use as reference.

In [ ]:
# prompt: machine learning module with sklearn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load the iris dataset
iris_data = load_iris()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(iris_data["data"], iris_data["target"], random_state=0)

# Create a KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)

# Train the classifier
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = knn.score(X_test, y_test)
print(accuracy)


0.9736842105263158


Actual work

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import csv
from pathlib import Path
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import BorderlineSMOTE
from imblearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score, classification_report, confusion_matrix, accuracy_score, roc_auc_score, roc_curve, precision_recall_curve, average_precision_score
from sklearn.metrics import homogeneity_score, silhouette_score
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import MiniBatchKMeans, DBSCAN


# Define a function to prep our data
def prep_data(df: pd.DataFrame) -> (np.ndarray, np.ndarray):
    """
    Convert the DataFrame into two variable
    X: data columns (V1 - V28)
    y: lable column
    """
    X = df.iloc[:, 2:30].values
    y = df.diffculty.values
    return X, y

# Define a function to create a scatter plot of our data and labels
def plot_data(X: np.ndarray, y: np.ndarray):
    plt.scatter(X[y == 0, 0], X[y == 0, 1], label="Class #0", alpha=0.5, linewidth=0.15)
    plt.scatter(X[y == 1, 0], X[y == 1, 1], label="Class #1", alpha=0.5, linewidth=0.15, c='r')
    plt.legend()
    return plt.show()

In [ ]:
#get dataset
datasheet_test = "https://raw.githubusercontent.com/Potatoed7/AI-FES-pynotebooks/blob/main/AI%20data%20-%20100%20only%20test.csv"
datasheet_test2 = "https://raw.githubusercontent.com/Potatoed7/AI-FES-pynotebooks/main/AI%20data%20-%20100%20only%20test.csv"

In [ ]:
#import the file into a dataframe, i.e. a "spreadsheet" in Python
dftest = pd.read_csv(datasheet_test2, nrows=99)

In [ ]:
dftest

Number 1  Operation  Number 2  Result  diffculty
0          1          3       -99   -99.0          3
1        -99          2        23  -122.0          3
2         73          3        78  5694.0          3
3         15          2        51   -36.0          2
4        -62          1        44   -18.0          2
..       ...        ...       ...     ...        ...
94       -38          3       -81  3078.0          3
95       -88          1       -88  -176.0          2
96        98          1        -8    90.0          1
97       -59          1       -97  -156.0          2
98        88          1       -98   -10.0          2

[99 rows x 5 columns]

# ***Working AI***

In [ ]:
# prompt: Using dataframe dftest: write a machine learning program using this dataset to give the difficulty of the equation between 'number 1' and 'number 2'

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier

# Load the data
df = dftest

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df[['Number 1','Operation','Number 2', 'Result']], df['diffculty'], test_size=0.2)

# Train a random forest classifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
print(y_pred)

# Evaluate the accuracy of the classifier
accuracy = model.score(X_test, y_test)
print(accuracy)


[1 3 4 2 3 1 2 1 2 3 2 2 3 3 2 2 3 3 2 2]
0.8


In [ ]:
X_test

Number 1  Operation  Number 2     Result
5          9          1        30    39.0000
36       -65          3       -30  1950.0000
61       -29          2        38   -67.0000
67       -56          4        36    -1.5600
3         15          2        51   -36.0000
28       -98          2        -7   -91.0000
13       -86          1        74   -12.0000
31       -69          2       -95    26.0000
29       -50          3       -40  2000.0000
10       -75          1       -40  -115.0000
83        88          4       -24    -3.6700
57        78          1         3    81.0000
12        37          4       -16    -2.3125
97       -59          1       -97  -156.0000
91       -76          2         6   -82.0000
76        -2          2       -68    66.0000
32       -20          2        28   -48.0000
11       -33          1        67    34.0000
80        -4          2        89   -93.0000
60        33          3       -30  -990.0000

In [ ]:
#using dataFrames?
test2 = pd.DataFrame([[78, 4, -8, -9.75]],columns = ['Number 1', 'Operation', 'Number 2', 'Result'])

print(test2)

   Number 1  Operation  Number 2  Result
0        78          4        -8   -9.75


In [ ]:
model.predict(test2)

array([2])

In [ ]:
dftest = pd.read_csv(datasheet_test2)

In [ ]:
dftest

Number 1  Operation  Number 2       Result  diffculty
0            1          3       -99   -99.000000        3.0
1          -99          2        23  -122.000000        3.0
2           73          3        78  5694.000000        3.0
3           15          2        51   -36.000000        2.0
4          -62          1        44   -18.000000        2.0
...        ...        ...       ...          ...        ...
1494        45          1       -61   -16.000000        NaN
1495       -39          3       -63  2457.000000        NaN
1496        39          2       -81   120.000000        NaN
1497       -50          3       -58  2900.000000        NaN
1498       -45          4        76    -0.592105        NaN

[1499 rows x 5 columns]

In [ ]:
dftest = dftest.drop(["diffculty"], axis=1)
#dftest = dftest.drop(columns=['diffculty'])

In [ ]:
dftest

Number 1  Operation  Number 2       Result
0            1          3       -99   -99.000000
1          -99          2        23  -122.000000
2           73          3        78  5694.000000
3           15          2        51   -36.000000
4          -62          1        44   -18.000000
...        ...        ...       ...          ...
1494        45          1       -61   -16.000000
1495       -39          3       -63  2457.000000
1496        39          2       -81   120.000000
1497       -50          3       -58  2900.000000
1498       -45          4        76    -0.592105

[1499 rows x 4 columns]

In [ ]:
y_pred = model.predict(dftest)

np.set_printoptions(threshold=np.inf)

In [ ]:
y_pred

array([3, 2, 3, 2, 2, 2, 2, 3, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2,
       4, 2, 4, 2, 2, 2, 2, 3, 3, 3, 2, 1, 3, 2, 3, 3, 3, 2, 2, 2, 2, 2,
       2, 4, 2, 1, 2, 2, 2, 2, 4, 3, 1, 2, 3, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       1, 2, 2, 2, 3, 2, 2, 4, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 2,
       1, 2, 2, 2, 3, 2, 3, 3, 1, 3, 1, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 3,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 2, 2, 2, 2, 4, 2, 2, 2, 3, 3, 2, 2, 2, 3, 4, 2, 2, 2,
       4, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 4, 2, 3, 1, 2, 2,
       1, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 1, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3,
       2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 1,
       2, 2, 2, 2, 2, 2, 3, 4, 4, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 1, 2, 4,
       2, 2, 2, 4, 4, 2, 3, 2, 4, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 1,
       2, 3, 2, 3, 3, 3, 2, 3, 2, 2, 2, 4, 3, 2, 1,

# **Making it better**

In [ ]:
# Train a random forest classifier
model = LogisticRegression()
model.fit(X_train, y_train)

# Evaluate the accuracy of the classifier
accuracy = model.score(X_test, y_test)
print(accuracy)

0.45


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
#testing if SMOTE improves the results

In [ ]:
from imblearn.over_sampling import RandomOverSampler
# Define which resampling method and which ML model to use in the pipeline
resampling = RandomOverSampler()
model = LogisticRegression(solver='liblinear')

pipeline = Pipeline([('SMOTE', resampling), ('Logistic Regression', model)])

# Split your data X and y, into a training and a test set and fit the pipeline onto the training data
X_train, X_test, y_train, y_test = train_test_split(df[['Number 1','Operation','Number 2', 'Result']], df['diffculty'], test_size=0.2, random_state=1)

pipeline.fit(X_train, y_train)
predicted = pipeline.predict(X_test)

print(pipeline.score(X_test, y_test))
# Obtain the results from the classification report and confusion matrix
#print('Classification report:\n', classification_report(y_test, predicted))
conf_mat = confusion_matrix(y_true=y_test, y_pred=predicted)
#print('Confusion matrix:\n', conf_mat)

0.4


In [ ]:
from imblearn.over_sampling import RandomOverSampler
# Define which resampling method and which ML model to use in the pipeline
resampling = RandomOverSampler()
model = RandomForestClassifier()

pipeline = Pipeline([('SMOTE', resampling), ('Logistic Regression', model)])

# Split your data X and y, into a training and a test set and fit the pipeline onto the training data
X_train, X_test, y_train, y_test = train_test_split(df[['Number 1','Operation','Number 2', 'Result']], df['diffculty'], test_size=0.2, random_state=1)

pipeline.fit(X_train, y_train)
predicted = pipeline.predict(X_test)

print(pipeline.score(X_test, y_test))

0.7


# ***Try to make it Gen AI***

In [ ]:
df = pd.read_csv(datasheet_test2)
df = df[:99]
print(df)
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['diffculty'], df[['Number 1','Operation','Number 2', 'Result']],  test_size=0.2)

# Train a random forest classifier
model2 = RandomForestClassifier()
model2.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model2.predict(X_test)
print(y_pred)

# Evaluate the accuracy of the classifier
accuracy = model2.score(X_test, y_test)
print(accuracy)

    Number 1  Operation  Number 2  Result  diffculty
0          1          3       -99   -99.0        3.0
1        -99          2        23  -122.0        3.0
2         73          3        78  5694.0        3.0
3         15          2        51   -36.0        2.0
4        -62          1        44   -18.0        2.0
..       ...        ...       ...     ...        ...
94       -38          3       -81  3078.0        3.0
95       -88          1       -88  -176.0        2.0
96        98          1        -8    90.0        1.0
97       -59          1       -97  -156.0        2.0
98        88          1       -98   -10.0        2.0

[99 rows x 5 columns]


AttributeError: 'Series' object has no attribute 'reshape'